### Create User
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe 3",
  "email": "john4@example.com",
  "password": "password123"
}

### Get All Users
GET {{baseUrl}}/users

### Get User by ID
GET {{baseUrl}}/users/f6daa33b-183e-4c86-b464-be0606b3ed3a

### Update User
PUT {{baseUrl}}/users/f6daa33b-183e-4c86-b464-be0606b3ed3a
Content-Type: application/json

{
  "name": "John Updated" 
}

### Delete User
DELETE {{baseUrl}}/users/f6daa33b-183e-4c86-b464-be0606b3ed3a
