### Create User
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Jossshn Doe22",
  "email": "joddasdhns224sss@example.com",
  "password": "pasasdassword123"
}

### Get All Users
GET {{baseUrl}}/users

### Get User by ID
GET {{baseUrl}}/users/d5c7f5ce-ae98-446f-8d61-4cdacbdf2ccc

### Update User
PUT {{baseUrl}}/users/d5c7f5ce-ae98-446f-8d61-4cdacbdf2ccc
Content-Type: application/json

{
  "name": "John Updated"  
}

### Delete User
DELETE {{baseUrl}}/users/d5c7f5ce-ae98-446f-8d61-4cdacbdf2ccc
