### Sign Up
POST {{baseUrl}}/auth/signup
Content-Type: application/json


{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "SecurePass123"
}

### Sign In
# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "12345678"
}
###

@myAccessToken = {{signin.response.body.accessToken}}
@myRefreshToken = {{signin.response.body.refresh_token}}
@myCsrfToken = {{signin.response.body.csrf_token}}

### Refresh Session
POST {{baseUrl}}/auth/refresh
Content-Type: application/json
X-CSRF-Token: {{myCsrfToken}}
Cookie: refresh_token={{myRefreshToken}}; csrf_token={{myCsrfToken}}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Cookie: refresh_token={{myRefreshToken}}

### Variables (replace with actual values from responses)
# @csrf_token = {{myCsrfToken}}
# @refresh_token = {{myRefreshToken}}
