auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 0 # ไม่จำเป็นต้องเปิด gRPC ออกนอก

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1

  # ใช้ memberlist สำหรับ ring (แก้ปัญหา empty ring)
  ring:
    kvstore:
      store: memberlist

# ตั้งค่า ring/cluster สำหรับโหมด single-process
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1

# memberlist ใช้ชื่อ host 'loki' ใน docker network เดียวกัน
memberlist:
  join_members:
    - loki

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13 # ใช้ v13 ล่าสุด (ถ้า image รองรับ)
      index:
        prefix: index_
        period: 24h

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 128

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  alertmanager_url: http://localhost:9093

# ยอมรับ log เก่าย้อนหลังช่วง bootstrap แรก (ลดลงภายหลังได้)
limits_config:
  allow_structured_metadata: false
  reject_old_samples: true
  reject_old_samples_max_age: 720h # 30 วัน (ตอนแรก), ค่อยลดเหลือ 168h ทีหลัง
