server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    # แปลงรูปแบบ log ของ Docker
    pipeline_stages:
      # - docker: {}
      - docker: {}
      - json:
          expressions:
            traceId: traceId
      - labels:
          traceId:

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container

      # ⬇️ ใช้ชื่อ label แบบ compose_service / compose_project
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project

      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream

      # ⬇️ ใช้ wildcard เผื่อ log rotation
      - source_labels: ['__meta_docker_container_id']
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/*-json.log
