apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields: # Logs → Trace: ดึง traceId จาก log แล้วลิงก์ไป Tempo
        - name: traceId
          matcherRegex: 'traceId[=:]\s*"?([a-f0-9-]{16,36})"?'
          url: '${__ds:Tempo}/trace/${__match:1}'
          datasourceUid: tempo
